# Generated by Django 4.2.1 on 2023-05-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster_url',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
