# Generated by Django 4.2.1 on 2023-05-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_film_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.FileField(upload_to='films/static/films'),
        ),
    ]
