# Generated by Django 4.2.1 on 2023-05-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_alter_film_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.CharField(default=0, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='trailer',
            field=models.CharField(default=0, max_length=512),
            preserve_default=False,
        ),
    ]
